name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # 1. Checar o repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # 3. Configurar o Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.9.5"

      # Entra no diretorio
      - name: Change directory to template folder
        run: cd template
    
      - name: Zip Lambda Function
        run: |
            cd src/Lambda-Function
            zip -r lambda_function.zip .

      # 4. Inicializar o Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./template

      # 5. Validar a configuração do Terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./template

      # 6. Executar o Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./template

      # 7. Aplicar a configuração do Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
